M48
; DRILL file KiCad 10.0.5-10.0.5~ubuntu24.04.1 date 2026-07-27T13:42:08
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-27T13:42:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5-10.0.5~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
%
G90
G05
T1
X213.0Y-101.679
X213.0Y-121.339
M30
